//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQueryDataTableInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blackrock_db_stock
    {
        public int id { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> stock_date { get; set; }
        public Nullable<double> stock_open { get; set; }
        public Nullable<double> stock_high { get; set; }
        public Nullable<double> stock_low { get; set; }
        public Nullable<double> stock_close { get; set; }
        public Nullable<double> stock_adj_close { get; set; }
        public Nullable<long> stock_volume { get; set; }
        public Nullable<double> stock_net { get; set; }
    }
}
